image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Couchbase
    command: cd /opt/couchbase/ && ./start-cb.sh
  - name: Log use
    command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=python-quickstart-repo&source=gitpod' > /dev/null
  - name: Start app
    init: cd src && python3 -m pip install -r requirements.txt
    command: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -u Administrator:password localhost:8091/pools/default/buckets/)" != "200" ]]; do sleep 5; done && flask run && gp await-port 5000 && gp preview $(gp url 5000)

# exposed ports
ports:
  - port: 5000
    onOpen: open-preview
  - port: 8091
    onOpen: open-browser
  - port: 8092-22000
    onOpen: ignore
  - port: 4369
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
