image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Couchbase
    command: ./startcb.sh
  - name: Log use
    command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=python-quickstart-repo&source=gitpod' > /dev/null
  - name: Start app
    init: python3 -m pip install -r src/requirements.txt
    command: cd src && while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -u Administrator:password localhost:8091/pools/default/buckets/)" != "200" ]]; do sleep 5; done && python3 db_init.py && (flask run &) && sleep 1 && socat TCP-LISTEN:8080,fork TCP4:localhost:5000

# exposed ports
ports:
  - port: 5000
    onOpen: ignore
  - port: 8080
    onOpen: open-preview
  - port: 8091
    onOpen: open-browser
  - port: 8092-22000
    onOpen: ignore
  - port: 4369
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true

vscode:
  extensions:
    - ms-python.python
